// import { QueryClient, QueryClientProvider, useQuery } from '@tanstack/react-query'
import Footer from './components/footer/footer'
import Header from './components/header/header'
import './globals.css'
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// const queryClient = new QueryClient()

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <QueryClientProvider client={queryClient}> */}
          <Header />
            {children}
          <Footer />
        {/* </QueryClientProvider> */}
      </body>
    </html>
  )
}
